### ISSUE TITLE
compiling 1 tiff from multiple sources

### ISSUE THREAD

**Issue by alexgman** [dgm9704/TIFF#2]
I need to be able to compile 1 tiff from multiple image files such as png/pdf/gif/jpeg. Is it possible to do this with this library?

**Comment by dgm9704** [comment]
Unfortunately not directly, no. The library only handles tiff files. But if you first use something else to convert the sources to tiff, the combination should be possible after that.
I have to say though that any tool that would be able to do the conversion, would most likely also be able to do the combination, which would make this library not needed.
I hope you find a solution that fits your need.

**Comment by dgm9704** [comment]
Closing this as it is outside the scope of this project, and better tools exist for requested functionality.
